package hipermvc.model;
// Generated 17/09/2019 12:50:38 by Hibernate Tools 4.3.1



/**
 * NotasitemId generated by hbm2java
 */
public class NotasitemId  implements java.io.Serializable {


     private long filial;
     private long sequencia;
     private long sequenciaitem;

    public NotasitemId() {
    }

    public NotasitemId(long filial, long sequencia, long sequenciaitem) {
       this.filial = filial;
       this.sequencia = sequencia;
       this.sequenciaitem = sequenciaitem;
    }
   
    public long getFilial() {
        return this.filial;
    }
    
    public void setFilial(long filial) {
        this.filial = filial;
    }
    public long getSequencia() {
        return this.sequencia;
    }
    
    public void setSequencia(long sequencia) {
        this.sequencia = sequencia;
    }
    public long getSequenciaitem() {
        return this.sequenciaitem;
    }
    
    public void setSequenciaitem(long sequenciaitem) {
        this.sequenciaitem = sequenciaitem;
    }


     @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotasitemId) ) return false;
		 NotasitemId castOther = ( NotasitemId ) other; 
         
		 return (this.getFilial()==castOther.getFilial())
 && (this.getSequencia()==castOther.getSequencia())
 && (this.getSequenciaitem()==castOther.getSequenciaitem());
   }
   
     @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getFilial();
         result = 37 * result + (int) this.getSequencia();
         result = 37 * result + (int) this.getSequenciaitem();
         return result;
   }   


}


