package hipermvc.model;
// Generated 17/09/2019 12:50:38 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Notas generated by hbm2java
 */

public class Notas  implements java.io.Serializable {
    
     private NotasId id;
     private BigDecimal valortotal;
     private Set notasitens = new HashSet(0);

    public Notas() {
    }
    
       public Set getNotasitens() {
        return notasitens;
    }

    public void setNotasitens(Set notasitens) {
        this.notasitens = notasitens;
    }

    
    public Notas(NotasId id) {
        this.id = id;
    }
    
    public Notas(NotasId id, BigDecimal valortotal) {
       this.id = id;
       this.valortotal = valortotal;
    }

    public Notas(NotasId notaid, double valor) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public NotasId getId() {
        return this.id;
    }
    
    public void setId(NotasId id) {
        this.id = id;
    }
    public BigDecimal getValortotal() {
        return this.valortotal;
    }
    
    public void setValortotal(BigDecimal valortotal) {
        this.valortotal = valortotal;
    }




}


